server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**

            - id: parking-space-service
              uri: lb://PARKING-SPACE-SERVICE
              predicates:
                - Path=/parking-space-service/**

            - id: vehicle-service
              uri: lb://VEHICLE-SERVICE
              predicates:
                - Path=/vehicle-service/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**