server:
  port: 8888
  servlet:
    context-path: /configuration-server

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LahiruChanak/ParkWare-smart_parking_system.git
          clone-on-start: true
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info