server:
  port: 8888
  servlet:
    context-path: /configuration-server

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LahiruChanak/ParkWare-smart_parking_system.git
          clone-on-start: true
          default-label: master
          username: LahiruChanak
          password: ENC(1FSZ5z3TFIydJYkmHNhMwMNVOy07XX2W10rvHMT71SvsNk0t8RK5KUdxbX1x3BILa5oi3Glj8vo=)
  profiles:
    active: git

jasypt:
  encryptor:
    password: qX4z9+YdLtRzMHRUdAp7XyDqZc4B0vAq+iG2C3D6aJ0=
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info