server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LahiruChanak/ParkWare-smart_parking_system.git
#         username: LahiruChanak
#         password: ENC(1FSZ5z3TFIydJYkmHNhMwMNVOy07XX2W10rvHMT71SvsNk0t8RK5KUdxbX1x3BILa5oi3Glj8vo=)
          clone-on-start: true
          default-label: master
          timeout: 10


#jasypt:
#  encryptor:
#    password: qX4z9+YdLtRzMHRUdAp7XyDqZc4B0vAq+iG2C3D6aJ0=
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: DEBUG